### ISSUE TITLE
Sets

### ISSUE THREAD

**Issue by tarcieri** [tjson/tjson-spec#22]
Should we add a data type for sets whose members are distinct and can map onto native language set types?

Edit: Under the changes in #35, it would look something like this:

``` json
{"example:S<i>": ["1", "2", "3"]}
```

**Comment by benlaurie** [comment]
I still think this is a reasonable plan.

**Comment by wbolster** [comment]
would members be required to be of the same type? some "native language sets" types require could require that (typed languages). if so the tag could maybe move one abstraction level up.

**Comment by tarcieri** [comment]
@wbolster #23 discusses that, but yes I think arrays and sets should require members be homogeneously typed
