### ISSUE TITLE
Canonicalization?

### ISSUE THREAD

**Issue by tarcieri** [tjson/tjson-spec#24]
Should there be a canonical form of TJSON? Some of the copy on the site references potential canonicalization.

If [objecthash](https://github.com/benlaurie/objecthash) can provide a unified content hash across various different versions of the same structure, is canonicalization even necessary?

**Comment by benlaurie** [comment]
objecthash was invented to avoid canonicalisation, so you can guess my answer.

**Comment by tarcieri** [comment]
Closing as: "won't do"
