### ISSUE TITLE
use "unicode string", not "utf-8 string"

### ISSUE THREAD

**Issue by wbolster** [tjson/tjson-spec#27]
the spec should use the term "unicode strings" (like all json strings), not "utf-8 strings", which refer to *encoded* text and is hence a byte format, not a text format.

**Comment by tarcieri** [comment]
Previous versions of the spec used "Unicode Strings". It was changed here to further emphasize that UTF-8 is the one-and-only allowable wire format for strings: 7247292a3171b9bd650cf2595a92b43202d25c4d

TJSON's tags refer to specific on-the-wire encodings, not (necessarily) to types. For example, while `b16`, `b32`, and `b64` can all be used to encode the same content, they have different on-the-wire representations.

**Comment by tarcieri** [comment]
I opened a meta-issue for clearly distinguishing on-the-wire data from the underling data structures: #31

**Comment by tarcieri** [comment]
Fixed in #35
