### ISSUE TITLE
Is base64 tolerant of padding?

### ISSUE THREAD

**Issue by mplewis** [tjson/tjson-spec#29]
The TJSON spec says the following about base32- and base64-encoded data:

> The encoded data should NOT be padded with "=" characters as it's stored within a quote-delimited string so its length is known in advance.

This does not seem clear to me. Does this mean TJSON parsers MUST reject padded base32 and base64 data, or that they MAY reject it? Can a lazy producer rely on consumers to parse padded data?

**Comment by tarcieri** [comment]
https://www.tjson.org/spec/#rfc.section.3.2.2

> All base32 strings in TJSON MUST be lower case, and MUST NOT include any padding with the '=' character. TJSON parsers MUST reject any documents containing upper case base32 characters or padding.

https://www.tjson.org/spec/#rfc.section.3.2.3

> All base64url strings in TJSON MUST NOT include any padding with the '=' character. TJSON parsers MUST reject any documents containing padded base64url strings.

These are also both covered in the examples file:

https://github.com/tjson/tjson-spec/blob/master/draft-tjson-examples.txt#L156
https://github.com/tjson/tjson-spec/blob/master/draft-tjson-examples.txt#L184

**Comment by mplewis** [comment]
Great! Thank you! :)
