### ISSUE TITLE
Should floats be encoded as strings? Or be excised altogether?

### ISSUE THREAD

**Issue by tarcieri** [tjson/tjson-spec#32]
Some people have suggested that, for consistency's sake, floats should be encoded as strings rather than leveraging the existing JSON syntax.

Floats certainly could be encoded as strings, and ones that extend the precision of the current floating point type (e.g. `d:` for double). That said, floating points aren't commonly used in TJSON's intended contexts (cryptographically authenticated data) due to the difficulty of normalizing them, so an alternative approach would be to completely get rid of them.

The argument for the current approach is that if people do actually care about using JSON floats as they exist today, the currently specified syntax will probably provide the most performant option for serializing/deserializing floats.

**Comment by gabber12** [comment]
Making Float also string would certainly increase consistency, are you considering booleans too?
Although precision should also be defined in that case which parsers would have to adhere to, i guess.

**Comment by tarcieri** [comment]
With the new syntax, I'm not sure I really care about the inconsistency:

``` json
{
  "array-example:A<O>": [
    {
      "string-example:s": "foobar",
      "binary-example:b64": "QklOQVJZ",
      "float-example:f": 0.42,
      "int-example:i": "42",
      "timestamp-example:t": "2016-11-06T22:27:34Z"
    }
  ]
}
```

I don't think it makes sense to needlessly use a string here, unless it's explicitly for expressing a wider floating point range.

Closing for now.
