### ISSUE TITLE
Nullability not described in spec

### ISSUE THREAD

**Issue by tarcieri** [tjson/tjson-spec#42]
Right now the spec makes no statements about nullability.

The simplest approach is to make TJSON non-nullable. An alternative to `null` values is optional object keys, something which maps more cleanly to e.g. Protobufs and languages with non-nullable type systems.

Should other usages of `null` be entertained, e.g. in arrays/sets or other non-scalars?

**Comment by mbj** [comment]
> The simplest approach is to make TJSON non-nullable.

Please that one. But:

You may want to support an explicit [option type](https://en.wikipedia.org/wiki/Option_type), where `null` from JSON is the instance of `Nothing`. It would allow to re-use the JSON primitive `null` but avoid the whole issue of nullability unless explicitly opted in for a specific field.

**Comment by tarcieri** [comment]
@mbj option types might make sense as part of #41, specifically for object members which are optional and can be omitted completely. This avoids having to support the `null` value at all, and better maps to formats with optional fields like Protobufs.

**Comment by tarcieri** [comment]
I am going to spec this as TJSON being non-nullable for now, explicitly rejecting any documents containing the `null` value.

**Comment by tarcieri** [comment]
Nullability explicitly disallowed in #46

**Comment by mbj** [comment]
> I am going to spec this as TJSON being non-nullable for now, explicitly rejecting any documents containing the null value.

Thx.
