### ISSUE TITLE
custom tags?

### ISSUE THREAD

**Issue by nahuel** [tjson/tjson-spec#45]
is planned to add custom tags to the spec? So you can define a new applicatin specific tag/type with the associated serializer/deserializer functions in a mechanism similar to https://github.com/edn-format/edn

**Comment by tarcieri** [comment]
Take a look at #41. There's some discussion of a sort of self-describing schema language embedded in an "outer envelope" of a document. Not likely to be supported soon, but I think it's what you're after.
